# client/railway.toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"  # We assume your Dockerfile is client/Dockerfile

[deploy]
startCommand = "" # or null if you don't need a custom command
# you can set things like healthcheckPath, restartPolicyType, etc.
